language: ruby

rvm:
  - 2.2.1

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/database.yml.travis spec/dummy/config/database.yml

script:
#  - RAILS_ENV=test bundle exec rake db:seed
#  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare --trace
  - bundle exec rake db:seed
  - bundle exec rspec spec/

addons:
  code_climate:
    repo_token:
      secure: krmY2kP9+LEvID554WgxDcuSbsfbYw0ynyV6bKHRllHYbZhhIFLgA8lc/bxDJCkojMO4ESAk+wRIVa7N9+5n27dsTOvt6OrYU7dkXa2ybbM95vkR1rL7PFru9WiAISCTGERkJMhpg5ARMCCX5b8KkGI6Xk+Jx8YVS4OZSp6jtDE=
